// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD73GE464YV6zgxz8tPXfQ_ovmuM8tHhvM',
    appId: '1:173526912110:web:95276257c73e0f2c0bea7f',
    messagingSenderId: '173526912110',
    projectId: 'testfirebase-3c004',
    authDomain: 'testfirebase-3c004.firebaseapp.com',
    storageBucket: 'testfirebase-3c004.firebasestorage.app',
    measurementId: 'G-32DW0YB7JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrhl4dpmdlAYtNVoLO4hiTcDZcEyV_EFc',
    appId: '1:173526912110:android:2017d14303d83c9b0bea7f',
    messagingSenderId: '173526912110',
    projectId: 'testfirebase-3c004',
    storageBucket: 'testfirebase-3c004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfX85QX-1QSTajvrsYOly6L36QSUdYsI',
    appId: '1:173526912110:ios:a1cc33e4b5e7e0980bea7f',
    messagingSenderId: '173526912110',
    projectId: 'testfirebase-3c004',
    storageBucket: 'testfirebase-3c004.firebasestorage.app',
    iosBundleId: 'com.example.testfirebase',
  );
}
